services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: planify
    restart: always
    ports:
      - "${PORT}:${PORT}" 
    env_file:
      - .env 
    depends_on:
      - mysql
      - redis
    command: sh -c "npx typeorm migration:run -d dist/src/database/data-source.js && node dist/src/main.js"

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}" 
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis_container
    restart: always
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}

volumes:
  mysql_data:
