export const ACTIONS = {
  TASK: {
    CREATED: 'TASK_CREATED',
    UPDATED: 'TASK_UPDATED',
    DELETED: 'TASK_DELETED',
    STATUS_CHANGED: 'TASK_STATUS_CHANGED',
    ASSIGNEE_CHANGED: 'TASK_ASSIGNEE_CHANGED',
  },
};
