export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PROJECT_REPOSITORY = 'PROJECT_REPOSITORY';
export const TASK_REPOSITORY = 'TASK_REPOSITORY';
export const ROLE_REPOSITORY = 'ROLE_REPOSITORY';
